### PR TITLE
I fixed the train during week3/philly stage

### PR DESCRIPTION
**Pull request by MemeHoovy**

### CODE REVIEW

**Comment by doggogit** [comment]
Wasn't the Train already fine within Week 3?

**Comment by MemeHoovy** [comment]
> Wasn't the Train already fine within Week 3?

it came without sound, and I fixed that

**Comment by doggogit** [comment]
> > Wasn't the Train already fine within Week 3?
> 
> it came without sound sometimes, and I fixed that

Oh, right, yeah, I keep forgetting that it does that sometimes. Good work on finding a fix. 👍

**Comment by MemeHoovy** [comment]
it was literally that simple lol

**Comment by doggogit** [comment]
Still, lol.

**Pull request merged**
