### PR TITLE
Mod Support [using Polymod]

### PR DESCRIPTION
**Pull request by Joalor64GH**
It's just some WIP modding support.

### CODE REVIEW

**Comment by doggogit** [comment]
Hi!

As of right now, I don't *think* that Feather will have its own separate modding support up until Gabi/BeastlyGhost finishes whatever she has on her to-do list.

I, myself, am not experienced with Haxe code and the engine (HaxeFlixel) itself, so, I really have no right to comment whether this code is good or bad, I'll leave it up to Gabi to review this PR and whether to accept or deny it. :)

**Comment by AltronMaxX** [comment]
I highly recommend to use openfl assets instead of sys FileSystem. OpenFlAssets can find mod files in default engine paths (in assets folder). It makes ModPaths unnecessary to use.

**Comment by AltronMaxX** [comment]
Also polymods hscript is broken especially with flixel states.

**Comment by AltronMaxX** [comment]
And the last, I think you forgot to add Debug class :)

**Comment by Joalor64GH** [comment]
Got it 👍

**Comment by AltronMaxX** [comment]
Oh, forgot about one thing. Polymod can try to load folder with empty name (if you push in ModCore.loadModsById() this array ['']). To avoid this you can replace this: 
```
if (ids.length == 0)
{
	Debug.logWarn('You attempted to load zero mods.');
}
else
{
	Debug.logInfo('Attempting to load ${ids.length} mods...');
}
```
To this:
```
var modsToLoad:Array<String> = [];
			
if (ids.length == 0)
{
	Debug.logWarn('You attempted to load zero mods.');
}
else
{
	if (ids[0] != '' && ids != null)
	{
		Debug.logInfo('Attempting to load ${ids.length} mods...');
		modsToLoad = ids;
	}
	else
	{
		modsToLoad = [];
	}
}
```
Also replace ```dirs: ids,``` to ```dirs: modsToLoad,```

**Comment by Joalor64GH** [comment]
okay cool

**Comment by AltronMaxX** [comment]
Looks like you didn't try to test your code

**Comment by doggogit** [comment]
Will turn on workflows, just in case.

**Comment by doggogit** [comment]
> > > Will turn on workflows, just in case.
> > 
> > 
> > It won't compile without Debug class.
> 
> Oh, sorry, this code doesn't use ModCore. That makes workflows ignore that

well, I turned them on anyway, so.. lol.

**Comment by BeastlyGhost** [comment]
gonna look through this and test it maybe

**Comment by AltronMaxX** [comment]
> gonna look through this and test it maybe

I advise you to replace all FileSystem functions to analogues from OpenFl Assets for properly work of polymod. There will be some problems with replacing readDirectory function, but I have some code to do it by openfl assets.

**Comment by BeastlyGhost** [comment]
> > gonna look through this and test it maybe
> 
> I advise you to replace all FileSystem functions to analogues from OpenFl Assets for properly work of polymod. There will be some problems with replacing readDirectory function, but I have some code to do it by openfl assets.

i will probably need a way to replace readDirectory as Forever (and by extension Feather) uses it pretty often

**Comment by AltronMaxX** [comment]
> > > gonna look through this and test it maybe
> > 
> > 
> > I advise you to replace all FileSystem functions to analogues from OpenFl Assets for properly work of polymod. There will be some problems with replacing readDirectory function, but I have some code to do it by openfl assets.
> 
> i will probably need a way to replace readDirectory as Forever (and by extension Feather) uses it pretty often

Well, first of all, it can`t list folders. Only files from this folder and/or subfolders. Is this option suitable for you?

**Comment by BeastlyGhost** [comment]
> Well, first of all, it can`t list folders. Only files from this folder and/or subfolders. Is this option suitable for you?

well, that's gonna be a problem, take UI Skins and Note Skins for example, they look for directories instead of files inside them, so simply replacing FileSystem in this case could be complicated

**Comment by AltronMaxX** [comment]
> > Well, first of all, it can`t list folders. Only files from this folder and/or subfolders. Is this option suitable for you?
> 
> well, that's gonna be a problem, take UI Skins and Note Skins for example, they look for directories instead of files inside them, so simply replacing FileSystem in this case could be complicated

OpenFl Assets list function returns path to file with given asset type to find. Maybe i can do something with paths to get folder from it.

**Comment by BeastlyGhost** [comment]
> OpenFl Assets list function returns path to file with given asset type to find. Maybe i can do something with paths to get folder from it.

gonna set you to contributor since in order to merge this i will need help

i don't know shit about polymod, so help is appreciated, and if it doesn't get merged, i will probably make something based on filesystem

**Comment by AltronMaxX** [comment]
> > OpenFl Assets list function returns path to file with given asset type to find. Maybe i can do something with paths to get folder from it.
> 
> gonna set you to contributor since in order to merge this i will need help
> 
> i don't know shit about polymod, so help is appreciated, and if it doesn't get merged, i will probably make something based on filesystem

I spended mounths to research all polymod functions and problems :)

**Comment by BeastlyGhost** [comment]
image
quick reminder that contributors can go ahead an make changes to this pull request by clicking here, stuff will be updated as i test polymod out

**Comment by BeastlyGhost** [comment]
merged the SScript Fork to the main branch because it seems to work fine

**Comment by BeastlyGhost** [comment]
mb

**Comment by Stilic** [comment]
i will do a pull request with my own mod shit soon
it will be much simpler (the mod handler will be just one file)

**Pull request closed without merging**
